(() => {
  'use strict';

  const LANGUAGES = {
    'zh-Hans': '简体中文', 'zh-Hant': '繁體中文', ja: '日本語', ko: '한국어', en: 'English',
    de: 'Deutsch', es: 'Español', fr: 'Français', it: 'Italiano', pt: 'Português', th: 'ไทย',
    my: 'မြန်မာ', vi: 'Tiếng Việt', km: 'ភាសាខ្មែរ', lo: 'ພາສາລາວ', id: 'Bahasa Indonesia', ms: 'Bahasa Melayu'
  };
  const NAV = {
    'zh-Hans':['佛典','十三经','经典目录','数据说明'], 'zh-Hant':['佛典','十三經','經典目錄','資料說明'],
    ja:['仏典','十三経','経典目録','データ説明'], ko:['불전','십삼경','경전 목록','데이터 안내'],
    en:['Sutras','Thirteen Sutras','Library','Data Guide'], de:['Sutren','Dreizehn Sutren','Katalog','Datenhinweise'],
    es:['Sutras','Trece sutras','Catálogo','Guía de datos'], fr:['Soutras','Treize soutras','Catalogue','Guide des données'],
    it:['Sutra','Tredici sutra','Catalogo','Guida ai dati'], pt:['Sutras','Treze sutras','Catálogo','Guia de dados'],
    th:['พระไตรปิฎก','พระสูตร 13 เล่ม','สารบัญคัมภีร์','คู่มือข้อมูล'], my:['ပိဋကတ်တော်','ဗုဒ္ဓကျမ်း ၁၃ စောင်','ကျမ်းစာရင်း','ဒေတာလမ်းညွှန်'],
    vi:['Kinh điển','Mười ba kinh','Thư mục kinh điển','Hướng dẫn dữ liệu'], km:['ព្រះត្រៃបិដក','១៣ ព្រះសូត្រ','បញ្ជីគម្ពីរ','ការណែនាំទិន្នន័យ'],
    lo:['ພະໄຕປິໂດກ','ພຣະສູດ 13 ເຫຼັ້ມ','ສາລະບານຄຳພີ','ຄູ່ມືຂໍ້ມູນ'], id:['Sutra','Tiga Belas Sutra','Katalog','Informasi Data'],
    ms:['Sutra','Tiga Belas Sutra','Katalog','Panduan Data']
  };
  const CTA = {
    'zh-Hans':'进入体验','zh-Hant':'進入體驗',ja:'体験する',ko:'체험하기',en:'Enter Experience',
    de:'Erleben',es:'Comenzar',fr:'Découvrir',it:'Inizia',pt:'Começar',th:'เข้าสู่ประสบการณ์',
    my:'အတွေ့အကြုံယူရန်',vi:'Trải nghiệm',km:'ចូលទៅកាន់បទពិសោធន៍',lo:'ເຂົ້າສູ່ປະສົບການ',
    id:'Mulai Pengalaman',ms:'Mulakan Pengalaman'
  };
  const EN = {
    skip:'Skip to main content', language:'Language', menuOpen:'Open menu', menuClose:'Close menu', home:'Home', navigation:'Navigation', blog:'Blog',
    thirteenIntro:'Browse verified primary CBETA editions while keeping alternate translations and recensions visible.',
    libraryIntro:'Browse available canonical editions by page; each item opens directly in the focused scripture reader.',
    dataIntro:'Understand the sources, current product boundaries, and production build status.', scopeTitle:'Collection scope',
    loading:'Loading the latest data…', read:'Read', alternates:'Other translations and editions', sourceId:'Source ID', translator:'Translator',
    source:'Source', languageLabel:'Language', relation:'Relation', completeness:'Completeness', recommended:'Recommended', versionTitle:'Title',
    filter:'Filter this page', totalSummary:'{total} total editions · showing {from}–{to}', pageSummary:'Page {page} of {pages} · {remaining} pages remaining',
    previous:'Previous', next:'Next', canonicalTitle:'Canonical text source', canonicalBody:'The reader loads canonical assets only from buddb.xhalo.co; the interface does not generate or rewrite scripture.',
    boundaryTitle:'Reader boundary', boundaryBody:'foread.xhalo.co focuses on scripture reading, editions, and reading settings. Catalog and explanatory pages live here.',
    searchTitle:'Search is not enabled', searchBody:'This reading phase does not include search, RAG, or generative Q&A, preserving a verifiable source trail.',
    buildVersion:'Data version', buildTime:'Build time', schema:'Schema', works:'Works', status:'Release status', loadError:'The latest data could not be loaded. Please try again shortly.',
    thirteenMetaDesc:'A curated collection of Thirteen Buddhist Sutras and verified CBETA reading gateway.',
    libraryMetaDesc:'Browse CBETA canonical catalog by page and open in xHalo Buddhist reader.',
    dataMetaDesc:'Data source, capabilities boundaries, and current build status of xHalo Buddhist.'
  };
  const LOCAL = {
    'zh-Hans': {skip:'跳到主要内容',language:'语言',menuOpen:'打开菜单',menuClose:'关闭菜单',home:'主页',navigation:'导航',blog:'博客',thirteenIntro:'从可靠的典籍家族中选择经核验的 CBETA 主版本，并保留其他译本与异本信息。',libraryIntro:'分页浏览可用典籍版本；每项直接进入专注的正文阅读器。',dataIntro:'了解典籍来源、当前能力边界与生产数据的构建状态。',scopeTitle:'收录范围',loading:'正在读取最新数据…',read:'阅读正文',alternates:'其他译本与异本',sourceId:'来源编号',translator:'译者',source:'来源',languageLabel:'语言',relation:'关系',completeness:'完整度',recommended:'推荐',versionTitle:'版本名称',filter:'筛选当前页',totalSummary:'共 {total} 个版本 · 当前显示 {from}–{to}',pageSummary:'第 {page} / {pages} 页 · 剩余 {remaining} 页',previous:'上一页',next:'下一页',canonicalTitle:'权威正文来源',canonicalBody:'正文只从 buddb.xhalo.co 的 canonical 资产读取，不由界面生成或改写。',boundaryTitle:'阅读器边界',boundaryBody:'foread.xhalo.co 专注正文阅读、版本切换 and 阅读设置；目录与说明集中在此站。',searchTitle:'当前不提供检索',searchBody:'此阅读阶段不接入搜索、RAG 或生成式问答，以保持来源可核验。',buildVersion:'数据版本',buildTime:'构建时间',schema:'模式版本',works:'作品总数',status:'发布状态',loadError:'暂时无法读取最新数据，请稍后重试。',thirteenMetaDesc:'佛教十三经专题集合与经过验证的 CBETA 阅读入口。',libraryMetaDesc:'分页浏览 CBETA 经典目录并进入 xHalo Buddhist 阅读器。',dataMetaDesc:'xHalo Buddhist 的数据来源、能力边界与当前构建状态。'},
    'zh-Hant': {skip:'跳到主要內容',language:'語言',menuOpen:'開啟選單',menuClose:'關閉選單',home:'主頁',navigation:'導航',blog:'博客',thirteenIntro:'從可靠的典籍家族中選擇經核驗的 CBETA 主版本，並保留其他譯本與異本資訊。',libraryIntro:'分頁瀏覽可用典籍版本；每項直接進入專注的正文閱讀器。',dataIntro:'了解典籍來源、目前能力邊界與生產資料的構建狀態。',scopeTitle:'收錄範圍',loading:'正在讀取最新資料…',read:'閱讀正文',alternates:'其他譯本與異本',sourceId:'來源編號',translator:'譯者',source:'來源',languageLabel:'語言',relation:'關係',completeness:'完整度',recommended:'推薦',versionTitle:'版本名稱',filter:'篩選目前頁',totalSummary:'共 {total} 個版本 · 目前顯示 {from}–{to}',pageSummary:'第 {page} / {pages} 頁 · 殘餘 {remaining} 頁',previous:'上一頁',next:'下一頁',canonicalTitle:'權威正文來源',canonicalBody:'正文只從 buddb.xhalo.co 的 canonical 資產讀取，不由介面生成或改寫。',boundaryTitle:'閱讀器邊界',boundaryBody:'foread.xhalo.co 專注正文閱讀、版本切換和閱讀設定；目錄與說明集中在此站。',searchTitle:'目前不提供檢索',searchBody:'此閱讀階段不接入搜尋、RAG 或生成式問答，以保持來源可核驗。',buildVersion:'資料版本',buildTime:'構建時間',schema:'模式版本',works:'作品總數',status:'發布狀態',loadError:'暫時無法讀取最新資料，請稍後重試。',thirteenMetaDesc:'佛教十三經專題集合與經過驗證的 CBETA 閱讀入口。',libraryMetaDesc:'分頁瀏覽 CBETA 經典目錄並进入 xHalo Buddhist 閱讀器。',dataMetaDesc:'xHalo Buddhist 的資料來源、能力邊界與目前構築狀態。'},
    ja:{skip:'メインコンテンツにスキップ',language:'言語',menuOpen:'メニューを開く',menuClose:'メニューを閉じる',home:'ホーム',navigation:'ナビ',blog:'ブログ',thirteenIntro:'信頼できる経典ファミリーから検証済みの CBETA マスターバージョンを選択し、他の訳本や異本情報も保持します。',libraryIntro:'利用可能な典籍バージョンをページごとに閲覧します。各項目から直接、フォーカスされた正文リーダーに入ります。',dataIntro:'典籍のソース、現在の機能の境界、および本番データのビルドステータスを理解します。',scopeTitle:'コレクション範囲',loading:'最新データを読み込み中…',read:'本文を読む',alternates:'その他の訳本・異本',sourceId:'ソースID',translator:'訳者',source:'ソース',languageLabel:'言語',relation:'関係',completeness:'完全性',recommended:'推奨',versionTitle:'バージョン名',filter:'このページを絞り込む',totalSummary:'計 {total} バージョン · 現在表示中 {from}–{to}',pageSummary:'第 {page} / {pages} ページ · 残り {remaining} ページ',previous:'前へ',next:'次へ',canonicalTitle:'公式データソース',canonicalBody:'本文は buddb.xhalo.co の canonical アセットのみから読み込まれ、インターフェースによって生成または書き換えられることはありません。',boundaryTitle:'リーダーの境界',boundaryBody:'foread.xhalo.co は本文の読経、バージョンの切り替え、読経設定に焦点を当てています。目録と説明ページはここにあります。',searchTitle:'検索は提供していません',searchBody:'この読経フェーズでは、検索、RAG、生成AIによるQ&Aは導入されておらず、検証可能なソースの追跡性を保持しています。',buildVersion:'データバージョン',buildTime:'ビルド時間',schema:'スキーマバージョン',works:'作品総数',status:'リリース状態',loadError:'一時的に最新データを読み込めません。しばらくしてからもう一度お試しください。',thirteenMetaDesc:'仏教十三経のキュレーションコレクションと検証済みのCBETA読経への入り口。',libraryMetaDesc:'CBETA公式目録をページごとに閲覧し、xHalo Buddhistリーダーで開きます。',dataMetaDesc:'xHalo Buddhistのデータソース、機能境界、および現在のビルドステータス。'},
    ko:{skip:'본문 바로가기',language:'언어',menuOpen:'메뉴 열기',menuClose:'메뉴 닫기',home:'홈',navigation:'탐색',blog:'블로그',thirteenIntro:'신뢰할 수 있는 경전 패밀리 중에서 검증된 CBETA 마스터 버전을 선택하고, 다른 번역본과 이본 정보도 보존합니다.',libraryIntro:'사용 가능한 경전 버전을 페이지별로 탐색합니다. 각 항목에서 즉시 집중된 본문 리더로 들어갑니다.',dataIntro:'경전 출처, 현재 기능 경계 및 프로덕션 데이터 빌드 상태를 이해합니다.',scopeTitle:'컬렉션 범위',loading:'최신 데이터를 불러오는 중…',read:'본문 읽기',alternates:'다른 번역본과 이본',sourceId:'소스 ID',translator:'역자',source:'출처',languageLabel:'언어',relation:'관계',completeness:'완전성',recommended:'추천',versionTitle:'버전 명칭',filter:'현재 페이지 필터',totalSummary:'총 {total} 개 버전 · 현재 표시 중 {from}–{to}',pageSummary:'제 {page} / {pages} 페이지 · 남은 페이지 {remaining}',previous:'이전',next:'다음',canonicalTitle:'공식 데이터 소스',canonicalBody:'본문은 buddb.xhalo.co의 canonical 자산에서만 로드되며, 인터페이스에서 생성하거나 재작성하지 않습니다.',boundaryTitle:'리더 경계',boundaryBody:'foread.xhalo.co는 본문 읽기, 버전 전환 및 읽기 설정에 집중합니다. 카탈로그 및 설명 페이지는 여기에 있습니다.',searchTitle:'검색을 제공하지 않음',searchBody:'이 읽기 단계에서는 검색, RAG 또는 생성형 Q&A를 지원하지 않으며 검증 가능한 출처 추적을 보존합니다.',buildVersion:'데이터 버전',buildTime:'빌드 시간',schema:'스키마 버전',works:'작품 총수',status:'출시 상태',loadError:'최신 데이터를 불러올 수 없습니다. 잠시 후 다시 시도해 주세요.',thirteenMetaDesc:'불교 십삼경의 큐레이션 컬렉션과 검증된 CBETA 독경 입구.',libraryMetaDesc:'CBETA 공식 목록을 페이지별로 탐색하고 xHalo Buddhist 리더에서 엽니다.',dataMetaDesc:'xHalo Buddhist의 데이터 소스, 기능 경계 및 현재 빌드 상태.'},
    de:{skip:'Zum Hauptinhalt springen',language:'Sprache',menuOpen:'Menü öffnen',menuClose:'Menü schließen',home:'Startseite',navigation:'Navigation',blog:'Blog',thirteenIntro:'Wählen Sie verifizierte CBETA-Masterversionen aus einer vertrauenswürdigen Textfamilie aus und behalten Sie andere Übersetzungen.',libraryIntro:'Durchsuchen Sie die verfügbaren kanonischen Ausgaben Seite für Seite; jeder Eintrag öffnet sich direkt im Lesemodus.',dataIntro:'Verstehen Sie die Quellen, die aktuellen Produktgrenzen und den Erstellungsstatus der Produktionsdaten.',scopeTitle:'Umfang der Sammlung',loading:'Neueste Daten werden geladen…',read:'Text lesen',alternates:'Andere Übersetzungen und Ausgaben',sourceId:'Quell-ID',translator:'Übersetzer',source:'Quelle',languageLabel:'Sprache',relation:'Beziehung',completeness:'Vollständigkeit',recommended:'Empfohlen',versionTitle:'Versionstitel',filter:'Diese Seite filtern',totalSummary:'Insgesamt {total} Versionen · Anzeige {from}–{to}',pageSummary:'Seite {page} von {pages} · {remaining} Seiten verbleibend',previous:'Zurück',next:'Weiter',canonicalTitle:'Kanonische Textquelle',canonicalBody:'Der Reader lädt kanonische Assets nur von buddb.xhalo.co; die Schnittstelle generiert oder schreibt Schriften nicht um.',boundaryTitle:'Grenzen des Readers',boundaryBody:'foread.xhalo.co konzentriert sich auf das Lesen von Schriften, Editionen und Leseeinstellungen. Katalog und Erklärungsseiten leben hier.',searchTitle:'Suche nicht aktiviert',searchBody:'Diese Lesephase beinhaltet keine Suche, RAG oder generative Fragen und Antworten, wodurch die Rückverfolgbarkeit der Quelle gewahrt bleibt.',buildVersion:'Datenversion',buildTime:'Erstellungszeit',schema:'Schemaversion',works:'Werke gesamt',status:'Veröffentlichungsstatus',loadError:'Neueste Daten konnten nicht geladen werden. Bitte versuchen Sie es in Kürze noch einmal.',thirteenMetaDesc:'Eine kuratierte Sammlung von dreizehn buddhistischen Sutren und ein verifiziertes CBETA-Lesetor.',libraryMetaDesc:'Durchsuchen Sie den kanonischen CBETA-Katalog Seite für Seite und öffnen Sie ihn im xHalo Buddhist Reader.',dataMetaDesc:'Datenquelle, Funktionsgrenzen und aktueller Build-Status von xHalo Buddhist.'},
    es:{skip:'Saltar al contenido principal',language:'Idioma',menuOpen:'Abrir menú',menuClose:'Cerrar menú',home:'Inicio',navigation:'Navegación',blog:'Blog',thirteenIntro:'Seleccione ediciones maestras CBETA verificadas de una familia de textos confiables, conservando otras traducciones y recensiones.',libraryIntro:'Explore las ediciones canónicas disponibles página por página; cada elemento se abre directamente en el lector de escrituras.',dataIntro:'Comprenda las fuentes, los límites actuales del producto y el estado de compilación de datos de producción.',scopeTitle:'Alcance de la colección',loading:'Cargando los últimos datos…',read:'Leer texto principal',alternates:'Otras traducciones y versiones',sourceId:'ID de origen',translator:'Traductor',source:'Origen',languageLabel:'Idioma',relation:'Relación',completeness:'Integridad',recommended:'Recomendado',versionTitle:'Título de la versión',filter:'Filtrar esta página',totalSummary:'{total} versiones en total · Mostrando {from}–{to}',pageSummary:'Página {page} de {pages} · Quedan {remaining} páginas',previous:'Anterior',next:'Siguiente',canonicalTitle:'Fuente de texto canónico',canonicalBody:'El lector carga activos canónicos solo desde buddb.xhalo.co; la interfaz no genera ni reescribe las escrituras.',boundaryTitle:'Límites del lector',boundaryBody:'foread.xhalo.co se centra en la lectura de escrituras, ediciones y configuraciones de lectura. El catálogo y las páginas explicativas viven aquí.',searchTitle:'Búsqueda no habilitada',searchBody:'Esta fase de lectura no incluye búsqueda, RAG o preguntas y respuestas generativas, preservando la trazabilidad de la fuente.',buildVersion:'Versión de datos',buildTime:'Hora de compilación',schema:'Esquema de versión',works:'Total de obras',status:'Estado de publicación',loadError:'No se pudieron cargar los últimos datos. Inténtelo de nuevo en breve.',thirteenMetaDesc:'Una colección seleccionada de Trece Sutras Budistas y portal de lectura verificado de CBETA.',libraryMetaDesc:'Explore el catálogo canónico de CBETA página por página y ábralo en el lector xHalo Buddhist.',dataMetaDesc:'Fuente de datos, límites de capacidad y estado de compilación actual de xHalo Buddhist.'},
    fr:{skip:'Passer au contenu principal',language:'Langue',menuOpen:'Ouvrir le menu',menuClose:'Fermer le menu',home:'Accueil',navigation:'Navigation',blog:'Blog',thirteenIntro:'Sélectionnez des éditions maîtresses CBETA vérifiées dans une famille de textes fiables, tout en conservant les autres traductions.',libraryIntro:'Parcourez les éditions canoniques disponibles page par page ; chaque élément s’ouvre directement dans le lecteur dédié.',dataIntro:'Comprenez les sources, les limites actuelles du produit et l’état de construction des données de production.',scopeTitle:'Portée de la collection',loading:'Chargement des dernières données…',read:'Lire le texte',alternates:'Autres traductions et éditions',sourceId:'ID de source',translator:'Traducteur',source:'Source',languageLabel:'Langue',relation:'Relation',completeness:'Complétude',recommended:'Recommandé',versionTitle:'Titre de la version',filter:'Filtrer cette page',totalSummary:'{total} versions au total · Affichage {from}–{to}',pageSummary:'Page {page} sur {pages} · {remaining} pages restantes',previous:'Précédent',next:'Suivant',canonicalTitle:'Source de texte canonique',canonicalBody:'Le lecteur charge des actifs canoniques uniquement depuis buddb.xhalo.co ; l’interface ne génère ni ne réécrit les écritures.',boundaryTitle:'Limites du lecteur',boundaryBody:'foread.xhalo.co se concentre sur la lecture, les éditions et les paramètres de lecture. Le catalogue et les pages explicatives résident ici.',searchTitle:'Recherche non activée',searchBody:'Cette phase de lecture n’inclut pas de recherche, RAG ou Q&A génératif, préservant la traçabilité des sources.',buildVersion:'Version des données',buildTime:'Heure de build',schema:'Schéma de version',works:'Total des œuvres',status:'Statut de publication',loadError:'Impossible de charger les dernières données. Veuillez réessayer sous peu.',thirteenMetaDesc:'Une collection sélectionnée de Treize Soutras Bouddhistes et passerelle de lecture vérifiée de CBETA.',libraryMetaDesc:'Parcourez le catalogue canonique de CBETA page par page et ouvrez-le dans le lecteur xHalo Buddhist.',dataMetaDesc:'Source de données, limites de capacité et statut de build actuel de xHalo Buddhist.'},
    it:{skip:'Passa al contenuto principale',language:'Lingua',menuOpen:'Apri menu',menuClose:'Chiudi menu',home:'Home',navigation:'Navigazione',blog:'Blog',thirteenIntro:'Seleziona le edizioni master CBETA verificate da una famiglia di testi affidabili, conservando le altre traduzioni.',libraryIntro:'Sfoglia le edizioni canoniche disponibili pagina per pagina; ogni elemento si apre direttamente nel lettore di testi.',dataIntro:'Comprendi le fonti, i limiti attuali del produto e lo stato di compilazione dei dati di produzione.',scopeTitle:'Ambito della raccolta',loading:'Caricamento dati recenti…',read:'Leggi testo',alternates:'Altre traduzioni e edizioni',sourceId:'ID sorgente',translator:'Traduttore',source:'Sorgente',languageLabel:'Lingua',relation:'Relazione',completeness:'Completezza',recommended:'Consigliato',versionTitle:'Titolo versione',filter:'Filtra questa pagina',totalSummary:'{total} versioni in totale · Visualizzazione {from}–{to}',pageSummary:'Pagina {page} di {pages} · {remaining} pagine rimanenti',previous:'Precedente',next:'Successivo',canonicalTitle:'Sorgente testo canonico',canonicalBody:'Il lettore carica asset canonici solo da buddb.xhalo.co; l’interfaccia non genera o riscrive le scritture.',boundaryTitle:'Limiti del lettore',boundaryBody:'foread.xhalo.co si concentra sulla lettura delle scritture, edizioni e impostazioni di lettura. Il catalogo e le pagine esplicative risiedono qui.',searchTitle:'Ricerca non abilitata',searchBody:'Questa fase di lettura non include ricerca, RAG o Q&A generativo, preservando la tracciabilità della fonte originale.',buildVersion:'Versione dati',buildTime:'Ora di compilazione',schema:'Schema versione',works:'Totale opere',status:'Stato di pubblicazione',loadError:'Impossibile caricare i dati più recenti. Riprova tra breve.',thirteenMetaDesc:'Una raccolta selezionata di Tredici Sutra Buddisti e portale di lettura verificato di CBETA.',libraryMetaDesc:'Sfoglia il catalogo canonico di CBETA pagina per pagina e aprilo nel lettore xHalo Buddhist.',dataMetaDesc:'Sorgente dati, limiti di capacità e stato di compilazione attuale di xHalo Buddhist.'},
    pt:{skip:'Ir para o conteúdo principal',language:'Idioma',menuOpen:'Abrir menu',menuClose:'Fechar menu',home:'Início',navigation:'Navegação',blog:'Blog',thirteenIntro:'Selecione edições master CBETA verificadas de uma família de textos confiáveis, mantendo outras traduções e edições visíveis.',libraryIntro:'Navegue pelas edições canônicas disponíveis página por página; cada item abre diretamente no leitor de escrituras.',dataIntro:'Entenda as fontes, os limites atuais do produto e o status de compilação dos dados de produção.',scopeTitle:'Escopo da coleção',loading:'Carregando os dados mais recentes…',read:'Ler texto principal',alternates:'Outras traduções e edições',sourceId:'ID de origem',translator:'Tradutor',source:'Fonte',languageLabel:'Idioma',relation:'Relação',completeness:'Completitude',recommended:'Recomendado',versionTitle:'Título da versão',filter:'Filtrar esta página',totalSummary:'{total} versões no total · Exibindo {from}–{to}',pageSummary:'Página {page} de {pages} · Restam {remaining} páginas',previous:'Anterior',next:'Seguinte',canonicalTitle:'Fonte de texto canônico',canonicalBody:'O leitor carrega ativos canônicos apenas de buddb.xhalo.co; a interface não gera ou reescreve escrituras.',boundaryTitle:'Limites do leitor',boundaryBody:'foread.xhalo.co concentra-se na leitura de escrituras, edições e configurações de leitura. O catálogo e as páginas explicativas residem aqui.',searchTitle:'Pesquisa não ativada',searchBody:'Esta fase de leitura não inclui pesquisa, RAG ou perguntas e respostas gerativas, preservando a rastreabilidade da fonte.',buildVersion:'Versão dos dados',buildTime:'Hora de compilação',schema:'Esquema da versão',works:'Total de obras',status:'Status de publicação',loadError:'Não foi possível carregar os dados mais recentes. Tente novamente em breve.',thirteenMetaDesc:'Uma coleção selecionada de Treze Sutras Budistas e portal de leitura verificado do CBETA.',libraryMetaDesc:'Navegue pelo catálogo canônico do CBETA página por página e abra no leitor xHalo Buddhist.',dataMetaDesc:'Fonte de dados, limites de capacidade e status de compilação atual do xHalo Buddhist.'},
    th:{skip:'ข้ามไปยังเนื้อหาหลัก',language:'ภาษา',menuOpen:'เปิดเมนู',menuClose:'ปิดเมนู',home:'หน้าหลัก',navigation:'นำทาง',blog:'บล็อก',thirteenIntro:'เลือกฉบับหลัก CBETA ที่ผ่านการตรวจสอบแล้ว และยังคงแสดงฉบับแปลและฉบับอื่นควบคู่กัน',libraryIntro:'เรียกดูเวอร์ชันคัมภีร์ที่ใช้งานได้ทีละหน้า ทุกรายการเปิดเข้าสู่โปรแกรมอ่านพระสูตรโดยตรง',dataIntro:'ทำความเข้าใจแหล่งข้อมูล ขอบเขตความสามารถปัจจุบัน และสถานะการสร้างข้อมูลการผลิต',scopeTitle:'ขอบเขตคอลเลกชัน',loading:'กำลังอ่านข้อมูลล่าสุด…',read:'อ่านพระสูตร',alternates:'ฉบับแปลและฉบับอื่น',sourceId:'รหัสแหล่งที่มา',translator:'ผู้แปล',source:'แหล่งที่มา',languageLabel:'ภาษา',relation:'ความสัมพันธ์',completeness:'ความสมบูรณ์',recommended:'แนะนำ',versionTitle:'ชื่อฉบับ',filter:'กรองหน้านี้',totalSummary:'ทั้งหมด {total} เวอร์ชัน · กำลังแสดง {from}–{to}',pageSummary:'หน้า {page} / {pages} · เหลืออีก {remaining} หน้า',previous:'ก่อนหน้า',next:'ถัดไป',canonicalTitle:'แหล่งข้อความหลักที่ถูกต้อง',canonicalBody:'ข้อความหลักโหลดจากไฟล์ canonical ของ buddb.xhalo.co เท่านั้น ไม่ได้สร้างหรือแต่งขึ้นมาใหม่',boundaryTitle:'ขอบเขตโปรแกรมอ่าน',boundaryBody:'foread.xhalo.co เน้นอ่านพระสูตร สลับเวอร์ชัน และตั้งค่าการอ่าน ส่วนสารบัญและรายละเอียดอยู่ในไซต์นี้',searchTitle:'ยังไม่เปิดให้ค้นหา',searchBody:'ขั้นตอนนี้ไม่มีการเชื่อมต่อระบบค้นหา, RAG หรือการตอบคำถามโดย AI เพื่อคงการตรวจสอบแหล่งที่มาได้จริง',buildVersion:'เวอร์ชันข้อมูล',buildTime:'เวลาที่สร้าง',schema:'เวอร์ชันสัญญา',works:'ผลงานทั้งหมด',status:'สถานะการเผยแพร่',loadError:'ไม่สามารถอ่านข้อมูลล่าสุดได้ชั่วคราว โปรดลองใหม่ในภายหลัง',thirteenMetaDesc:'ชุดสะสมพระสูตรพุทธศาสนา 13 เล่มและช่องทางเข้าอ่าน CBETA ที่ผ่านการรับรอง',libraryMetaDesc:'เรียกดูสารบัญ canonical ของ CBETA ทีละหน้าและเปิดอ่านในเครื่องอ่าน xHalo Buddhist',dataMetaDesc:'แหล่งข้อมูล ขอบเขตความสามารถ และสถานะบิลด์ปัจจุบันของ xHalo Buddhist.'},
    my:{skip:'အဓိကအကြောင်းအရာသို့ သွားရန်',language:'ဘာသာစကား',menuOpen:'မီနူးဖွင့်ရန်',menuClose:'မီနူးပိတ်ရန်',home:'ပင်မ',navigation:'လမ်းညွှန်',blog:'ဘလော့ဂ်',thirteenIntro:'ယုံကြည်စိတ်ချရသော မူရင်းကျမ်းစာစုများထဲမှ စိစစ်ပြီး CBETA မူရင်းဗားရှင်းကို ရွေးချယ်ပြီး အခြားဘာသာပြန်များနှင့် မူကွဲများ၏ အချက်အလက်ကို ပြသထားသည်။',libraryIntro:'ရရှိနိုင်သော ကျမ်းစာမူများကို စာမျက်နှာအလိုက် ဖတ်ရှုပါ၊ အကြောင်းအရာတစ်ခုချင်းစီသည် စာဖတ်စနစ်သို့ တိုက်ရိုက်ရောက်ရှိမည်။',dataIntro:'ကျမ်းစာရင်းမြစ်၊ လက်ရှိစနစ်ကန့်သတ်ချက်နှင့် ဒေတာတည်ဆောက်မှုအခြေအနေကို နားလည်စေရန်။',scopeTitle:'စုစည်းမှုအကျုံးဝင်မှု',loading:'နောက်ဆုံးဒေတာကို ရယူနေသည်…',read:'ကျမ်းဖတ်ရန်',alternates:'အခြားဗားရှင်းနှင့် ဘာသာပြန်များ',sourceId:'ကျမ်းနံပါတ်',translator:'ဘာသာပြန်သူ',source:'အရင်းအမြစ်',languageLabel:'ဘာသာစကား',relation:'ဆက်စပ်မှု',completeness:'ပြည့်စုံမှု',recommended:'အကြံပြုချက်',versionTitle:'ဗားရှင်းအမည်',filter:'ဤစာမျက်နှာကို စစ်ထုတ်ရန်',totalSummary:'စုစုပေါင်း {total} ဗားရှင်း · ပြသနေသည် {from}–{to}',pageSummary:'စာမျက်နှာ {page} / {pages} · ကျန်ရှိသောစာမျက်နှာ {remaining}',previous:'ယခင်',next:'နောက်သို့',canonicalTitle:'ယုံကြည်စိတ်ချရသော မူရင်းကျမ်းစာရင်း',canonicalBody:'ကျမ်းစာများကို buddb.xhalo.co ရှိ canonical မှသာ ရယူပြီး မျက်နှာပြင်မှ ပြင်ဆင်ရေးသားခြင်း မပြုလုပ်ပါ။',boundaryTitle:'စာဖတ်စနစ်နယ်နိမိတ်',boundaryBody:'foread.xhalo.co သည် ကျမ်းစာဖတ်ရှုခြင်း၊ ဗားရှင်းပြောင်းခြင်းနှင့် စาဖတ်ဆက်တင်များအတွက်သာဖြစ်ပြီး ကျမ်းစာရင်းနှင့် ရှင်းလင်းချက်များကို ဤဆိုက်တွင် ထားရှိသည်။',searchTitle:'ရှာဖွေမှုမရနိုင်သေးပါ',searchBody:'ဤအဆင့်တွင် စာသားရှာဖွေမှု၊ RAG သို့မဟုတ် AI Q&A တို့ကို ထည့်သွင်းထားခြင်းမရှိဘဲ ကျမ်းစာစစ်မှန်မှုကိုသာ ထိန်းရှိမ်းသည်။',buildVersion:'ဒေတာဗားရှင်း',buildTime:'တည်ဆောက်ချိန်',schema:'စနစ်ဗားရှင်း',works:'စုစုပေါင်းကျမ်းစာ',status:'ထုတ်ပြန်မှုအခြေအနေ',loadError:'လတ်တလောဒေတာကို ရယူ၍မရနိုင်ပါ၊ ခဏအကြာမှ ပြန်ကြိုးစားပါ။',thirteenMetaDesc:'ဗုဒ္ဓဘာသာကျမ်း ၁၃ စောင်နှင့် စိစစ်ပြီး CBETA ကျမ်းဖတ်ရှုရန် ဝင်ပေါက်။',libraryMetaDesc:'CBETA တရားဝင်ကျမ်းစာရင်းကို စာမျက်နှาအလိုက် ဖတ်ရှုပြီး xHalo Buddhist စာဖတ်စနစ်တွင် ဖွင့်ပါ။',dataMetaDesc:'xHalo Buddhist ၏ ဒေတာအရင်းအမြစ်၊ စနစ်ကန့်သတ်ချက်နှင့် လက်ရှိတည်ဆောက်မှုအခြေအနေ။'},
    vi:{skip:'Chuyển đến nội dung chính',language:'Ngôn ngữ',menuOpen:'Mở thực đơn',menuClose:'Đóng thực đơn',home:'Trang chủ',navigation:'Điều hướng',blog:'Blog',thirteenIntro:'Chọn ấn bản CBETA chính thức đã xác minh từ hệ kinh điển đáng tin cậy, giữ lại thông tin dịch bản và dị bản.',libraryIntro:'Duyệt tìm ấn bản kinh điển khả dụng theo trang; mỗi mục dẫn trực tiếp đến trình đọc chánh văn.',dataIntro:'Hiểu về nguồn kinh điển, ranh giới năng lực hiện tại và trạng thái xây dựng dữ liệu.',scopeTitle:'Phạm vi sưu tập',loading:'Đang đọc dữ liệu mới nhất…',read:'Đọc chánh văn',alternates:'Bản dịch và dị bản khác',sourceId:'Mã nguồn',translator:'Dịch giả',source:'Nguồn',languageLabel:'Ngôn ngữ',relation:'Quan hệ',completeness:'Độ hoàn chỉnh',recommended:'Khuyên dùng',versionTitle:'Tên phiên bản',filter:'Lọc trang hiện tại',totalSummary:'Tổng {total} phiên bản · Hiển thị {from}–{to}',pageSummary:'Trang {page} / {pages} · Còn lại {remaining} trang',previous:'Trang trước',next:'Trang sau',canonicalTitle:'Nguồn chánh văn uy tín',canonicalBody:'Chánh văn chỉ đọc từ tài sản canonical của buddb.xhalo.co, không tự sinh hay sửa đổi văn bản.',boundaryTitle:'Ranh giới trình đọc',boundaryBody:'foread.xhalo.co tập trung đọc chánh văn, chuyển phiên bản và cài đặt đọc; danh mục và giải thích ở trang này.',searchTitle:'Hiện chưa hỗ trợ tìm kiếm',searchBody:'Giai đoạn này không tích hợp tìm kiếm, RAG hay Q&A AI để giữ tính xác thực của nguồn dẫn.',buildVersion:'Phiên bản dữ liệu',buildTime:'Thời gian dựng',schema:'Bản schema',works:'Tổng tác phẩm',status:'Trạng thái phát hành',loadError:'Tạm thời không thể đọc dữ liệu mới, vui lòng thử lại sau.',thirteenMetaDesc:'Bộ sưu tập chọn lọc Mười ba kinh Phật giáo và lối vào đọc CBETA đã xác minh.',libraryMetaDesc:'Duyệt danh mục canonical CBETA theo trang và mở trong trình đọc xHalo Buddhist.',dataMetaDesc:'Nguồn dữ liệu, ranh giới khả năng và trạng thái xây dựng hiện tại của xHalo Buddhist.'},
    km:{skip:'រំលងទៅមាតិកាចម្បង',language:'ភាសា',menuOpen:'បើកម៉ឺនុយ',menuClose:'បិទម៉ឺនុយ',home:'ទំព័រដើម',navigation:'ការរុករក',blog:'ប្លុក',thirteenIntro:'ជ្រើសរើសកំណែ CBETA ផ្លូវការដែលបានផ្ទៀងទុកពីបណ្តុំគម្ពីរដែលអាចទុកចិត្តបាន និងរក្សាទុកព័ត៌មានបកប្រែផ្សេងទៀត។',libraryIntro:'រកមើលកំណែគម្ពីរដែលមានតាមទំព័រនីមួយៗ ដែលនាំទៅកាន់កម្មវិធីអានអត្ថបទចម្បងដោយផ្ទាល់។',dataIntro:'ស្វែងយល់អំពីប្រភពគម្ពីរ ដែនកំណត់សមត្ថភាពបច្ចុប្បន្ន និងស្ថានភាពបង្កើតទិន្នន័យផលិតកម្ម។',scopeTitle:'វិសាលភាពនៃការប្រមូល',loading:'កំពុងអានទិន្នន័យចុងក្រោយ…',read:'អានអត្ថបទចម្បង',alternates:'ការបកប្រែ និងកំណែផ្សេងទៀត',sourceId:'លេខសម្គាល់ប្រភព',translator:'អ្នកបកប្រែ',source:'ប្រភព',languageLabel:'ភាសា',relation:'ទំនាក់ទំនង',completeness:'ភាពពេញលេញ',recommended:'ណែនាំ',versionTitle:'ឈ្មោះកំណែ',filter:'ចម្រោះទំព័រនេះ',totalSummary:'សរុប {total} កំណែ · កំពុងបង្ហាញ {from}–{to}',pageSummary:'ទំព័រ {page} / {pages} · នៅសល់ {remaining} ទំព័រ',previous:'មុន',next:'បន្ទាប់',canonicalTitle:'ប្រភពអត្ថបទផ្លូវការ',canonicalBody:'អត្ថបទចម្បងត្រូវបានអានពី canonical របស់ buddb.xhalo.co ប៉ុណ្ណោះ មិនត្រូវបានបង្កើតដោយចំណុចប្រទាក់ឡើយ។',boundaryTitle:'ដែនកំណត់កម្មវិធីអាន',boundaryBody:'foread.xhalo.co ផ្តោតលើการអាន ការផ្លាស់ប្តូរកំណែ និងการកំណត់การอាន រីឯបញ្ជីគម្ពីរ និងការណែនាំគឺនៅលើគេហទំព័រនេះ។',searchTitle:'មិនទាន់ផ្តល់ការស្វែងរក',searchBody:'ដំណាក់កាលអាននេះមិនភ្ជាប់ទៅការស្វែងរក RAG ឬ AI សំណួរ-ចម្លើយឡើយ ដើម្បីរក្សាការផ្ទៀងផ្ទាត់ប្រភពដើម។',buildVersion:'កំណែទិន្នន័យ',buildTime:'ពេលវេលាស្ថាបនា',schema:'កំណែ schema',works:'ស្នាដៃសរុប',status:'ស្ថានភាពចេញផ្សាយ',loadError:'មិនអាចអានទិន្នន័យថ្មីៗបានទេ សូមព្យាយាមម្តងទៀតនៅពេលក្រោយ។',thirteenMetaDesc:'បណ្តុំគម្ពីរពុទ្ធសាសនា ១៣ ព្រះសូត្រ និងច្រកចូលអាន CBETA ដែលបានផ្ទៀងបំពេញ។',libraryMetaDesc:'រកមើលកាតាឡុកផ្លូវការរបស់ CBETA តាមទំព័រ និងបើកក្នុងកម្មវិធីអាន xHalo Buddhist។',dataMetaDesc:'ប្រភពទិន្នន័យ ដែនកំណត់សមត្ថភាព និងស្ថានភាពស្ថាបនាបច្ចុប្បន្នរបស់ xHalo Buddhist។'},
    lo:{skip:'ຂ້າມໄປຫາເນື້ອຫາຫຼັກ',language:'ພາສາ',menuOpen:'ເປີດເມນູ',menuClose:'ປິດເມນູ',home:'ໜ້າຫຼັກ',navigation:'ນຳທາງ',blog:'ບລັອກ',thirteenIntro:'ເລືອກສະບັບຫຼັກ CBETA ທີ່ຜ່ານການກວດສອບແລ້ວຈາກຄຳພីທີ່ເຊື່ອຖືໄດ້ ແລະຍັງຄົງສະແດງສະບับແປ ແລະສະບັບອື່ນຄວບຄູ່ກັນ',libraryIntro:'ເອີ້ນເບິ່ງເວີຊັນຄຳພີທີ່ມີຢູ່ເທື່ອລະໜ້າ ທຸກລາຍການເປີດເຂົ້າສູ່ໂປຣແກຣມອ່ານພຣະສູດໂດຍກົງ',dataIntro:'ເຮັດຄວາມເຂົ້າໃຈແຫຼ່ງຂໍ້ມູນ ຂອບເຂດຄວາມສາມາດປັດຈຸບັນ ແລະສະຖານະການສ້າງຂໍ້ມູນການຜະລິດ',scopeTitle:'ຂອບເຂດຄໍເລັກຊັນ',loading:'ກຳລັງອ່ານຂໍ້ມູນຫຼ້າສຸດ…',read:'ອ່ານພຣະສູດ',alternates:'ສະບับແປ ແລະສະບับອື່ນ',sourceId:'ລະຫັດແຫຼ່ງທີ່ມາ',translator:'ຜູ້ແປ',source:'ແຫຼ່ງທີ່ມາ',languageLabel:'ພາສາ',relation:'ຄວາມສຳພັນ',completeness:'ຄວາມສົມບູນ',recommended:'ແນະນຳ',versionTitle:'ຊື່ສະบັບ',filter:'ກັ່ນຕອງໜ້ານີ້',totalSummary:'ທັງໝົດ {total} ເວີຊັນ · ກຳລັງສະແດງ {from}–{to}',pageSummary:'ໜ້າ {page} / {pages} · ເຫຼືອອີກ {remaining} ໜ້າ',previous:'ກ່ອນໜ້າ',next:'ຖັດໄປ',canonicalTitle:'ແຫຼ່ງຂໍ້ຄວາມຫຼັກທີ່ຖືກຕ້ອງ',canonicalBody:'ຂໍ້ຄວາມຫຼັກໂຫຼດຈາກໄຟລ໌ canonical ຂອງ buddb.xhalo.co ເທົ່ານັ້ນ ບໍ່ໄດ້ສ້າງ ຫຼືແຕ່ງຂຶ້ນມາໃໝ່',boundaryTitle:'ຂອບເຂດໂປຣແກຣມອ່ານ',boundaryBody:'foread.xhalo.co ເນັ້ນອ່ານພຣະສູດ ສະຫຼັບເວີຊັນ ແລະຕັ້ງຄ່າການອ່ານ ສ່ວນສາລະບານ ແລະລายລະອຽດຢູ່ໃນໄຊຕ໌ນີ້',searchTitle:'ຍັງບໍ່ເປີດໃຫ້ຄົ້ນຫາ',searchBody:'ຂັ້ນຕອນນີ້ບໍ່ມີການເຊື່ອມຕໍ່ລະບົບຄົ້ນຫາ, RAG ຫຼືການຕອບຄຳຖามໂດຍ AI ເພື່ອຄົງການກວດສອບແຫຼ່ງທີ່ມາໄດ້ຈິງ',buildVersion:'ເວີຊັນຂໍ້ມູນ',buildTime:'ເວລາທີ່ສ້າງ',schema:'ເວີຊັນສັນຍາ',works:'ຜົນງານທັງໝົດ',status:'ສະຖານະການເຜີຍແຜ່',loadError:'ບໍ່ສາມາດອ່ານຂໍ້ມູນຫຼ້າສຸດໄດ້ຊົ່ວຄາວ ກະລຸນາລອງໃໝ່ໃນພາຍຫຼັງ',thirteenMetaDesc:'ຊຸດສະສົມພຣະສູດພຸດທະສາສະໜา 13 ເຫຼັ້ມ ແລະຊ່ອງທາງເຂົ້າອ່ານ CBETA ທີ່ຜ່ານການຮັບຮອງ',libraryMetaDesc:'ເອີ້ນເບິ່ງສາລະບານ canonical ၏ CBETA ເທື່ອລະໜ້າ ແລະເປີດອ່ານໃນເຄື່ອງອ່ານ xHalo Buddhist',dataMetaDesc:'ແຫຼ່ງຂໍ້ມູນ ຂອບເຂດຄວາມສາມາດ ແລະສະຖານະບິລດ໌ປັດຈຸບັນຂອງ xHalo Buddhist.'},
    id:{skip:'Lompati ke konten utama',language:'Bahasa',menuOpen:'Buka menu',menuClose:'Tutup menu',home:'Beranda',navigation:'Navigasi',blog:'Blog',thirteenIntro:'Pilih edisi master CBETA terverifikasi dari keluarga naskah tepercaya, dengan tetap menampilkan terjemahan dan versi lainnya.',libraryIntro:'Jelajahi edisi naskah yang tersedia halaman demi halaman; setiap item langsung membuka pembaca teks fokus.',dataIntro:'Pahami sumber data, batas kemampuan saat ini, dan status pembangunan data produksi.',scopeTitle:'Cakupan koleksi',loading:'Sedang membaca data terbaru…',read:'Baca teks utama',alternates:'Terjemahan & versi lainnya',sourceId:'ID Sumber',translator:'Penerjemah',source:'Sumber',languageLabel:'Bahasa',relation:'Hubungan',completeness:'Kelengkapan',recommended:'Rekomendasi',versionTitle:'Nama versi',filter:'Filter halaman ini',totalSummary:'Total {total} versi · Menampilkan {from}–{to}',pageSummary:'Halaman {page} / {pages} · Tersisa {remaining} halaman',previous:'Sebelumnya',next:'Berikutnya',canonicalTitle:'Sumber teks resmi',canonicalBody:'Teks utama hanya dibaca dari aset canonical buddb.xhalo.co, tidak dibuat atau diubah oleh antarmuka.',boundaryTitle:'Batasan pembaca',boundaryBody:'foread.xhalo.co berfokus pada pembacaan teks, peralihan versi, dan pengaturan membaca; katalog dan penjelasan ada di situs ini.',searchTitle:'Pencarian tidak tersedia',searchBody:'Tahap pembacaan ini tidak menghubungkan pencarian, RAG, atau AI Q&A untuk menjaga ketertelusuran sumber.',buildVersion:'Versi data',buildTime:'Waktu pembuatan',schema:'Versi skema',works:'Total karya',status:'Status rilis',loadError:'Sementara tidak dapat membaca data terbaru, silakan coba lagi nanti.',thirteenMetaDesc:'Koleksi kurasi Tiga Belas Sutra Buddha dan gerbang pembacaan CBETA terverifikasi.',libraryMetaDesc:'Jelajahi katalog resmi CBETA halaman demi halaman dan buka di pembaca xHalo Buddhist.',dataMetaDesc:'Sumber data, batas kemampuan, dan status build saat ini dari xHalo Buddhist.'},
    ms:{skip:'Langkau ke kandungan utama',language:'Bahasa',menuOpen:'Buka menu',menuClose:'Tutup menu',home:'Laman utama',navigation:'Navigasi',blog:'Blog',thirteenIntro:'Pilih edisi induk CBETA disahkan dari keluarga naskah dipercayai, dengan mengekalkan paparan terjemahan dan versi lain.',libraryIntro:'Jelajahi edisi naskah yang tersedia halaman demi halaman; setiap item terus membuka pembaca teks fokus.',dataIntro:'Fahami sumber data, had keupayaan semasa, dan status pembinaan data pengeluaran.',scopeTitle:'Skop koleksi',loading:'Sedang membaca data terbaru…',read:'Baca teks utama',alternates:'Terjemahan & versi lain',sourceId:'ID Sumber',translator:'Penterjemah',source:'Sumber',languageLabel:'Bahasa',relation:'Hubungan',completeness:'Kelengkapan',recommended:'Rekomendasi',versionTitle:'Nama versi',filter:'Tapis halaman ini',totalSummary:'Jumlah {total} versi · Menunjukkan {from}–{to}',pageSummary:'Halaman {page} / {pages} · Berbaki {remaining} halaman',previous:'Sebelumnya',next:'Seterusnya',canonicalTitle:'Sumber teks rasmi',canonicalBody:'Teks utama hanya dibaca dari aset canonical buddb.xhalo.co, tidak dijana ou alterado pela interface.',boundaryTitle:'Sempadan pembaca',boundaryBody:'foread.xhalo.co menumpukan pada pembacaan teks, pertukaran versi, dan tetapan membaca; katalog dan penjelasan ada di laman ini.',searchTitle:'Carian tidak disediakan',searchBody:'Tahap pembacaan ini tidak menghubungkan carian, RAG, atau AI Q&A untuk mengekalkan kebolehkesanan sumber.',buildVersion:'Versi data',buildTime:'Waktu pembuatan',schema:'Versi skema',works:'Jumlah karya',status:'Status keluaran',loadError:'Sementara tidak dapat membaca data terbaru, sila cuba lagi nanti.',thirteenMetaDesc:'Koleksi kurasi Tiga Belas Sutra Buddha dan gerbang pembacaan CBETA yang disahkan.',libraryMetaDesc:'Jelajahi katalog rasmi CBETA halaman demi halaman dan buka di pembaca xHalo Buddhist.',dataMetaDesc:'Sumber data, had keupayaan, dan status build semasa dari xHalo Buddhist.'}
  };
  const params = new URLSearchParams(location.search);
  const requested = params.get('lang');
  const stored = localStorage.getItem('lang');
  const browser = navigator.language;
  const locale = LANGUAGES[requested] ? requested : LANGUAGES[stored] ? stored : browser.startsWith('zh-TW') || browser.startsWith('zh-HK') ? 'zh-Hant' : LANGUAGES[browser] ? browser : 'zh-Hans';
  const copy = {...EN, ...(LOCAL[locale] || {}), enter:CTA[locale] || CTA.en};
  const nav = NAV[locale] || NAV.en;
  const page = document.body.dataset.page;
  const titles = {thirteen:nav[1],library:nav[2],data:nav[3]};

  function format(value, values) { return Object.entries(values).reduce((text, [key, val]) => text.replace(`{${key}}`, String(val)), value); }
  function el(tag, className, text) { const node=document.createElement(tag); if(className)node.className=className;if(text!==undefined)node.textContent=text;return node; }
  function safeId(value, length=128) { return typeof value==='string' && value.length<=length && /^[A-Za-z0-9._-]+$/.test(value); }
  function readerHref(sourceId, language, query='') { return `https://foread.xhalo.co/${encodeURIComponent(locale)}/read/cbeta/${encodeURIComponent(sourceId)}/${encodeURIComponent(language)}/cbeta${query}`; }
  function pageHref(path, extra={}) { const url=new URL(path,location.origin);url.searchParams.set('lang',locale);Object.entries(extra).forEach(([key,value])=>url.searchParams.set(key,String(value)));return `${url.pathname}${url.search}`; }

  document.documentElement.lang=locale;
  document.title=`${titles[page] || 'xHalo Buddhist'} · xHalo Buddhist`;
  const ogTitleMeta = document.querySelector('meta[property="og:title"]');
  if (ogTitleMeta) ogTitleMeta.setAttribute('content', document.title);
  const descKey = `${page}MetaDesc`;
  if (copy[descKey]) {
    const descMeta = document.querySelector('meta[name="description"]');
    if (descMeta) descMeta.setAttribute('content', copy[descKey]);
    const ogDescMeta = document.querySelector('meta[property="og:description"]');
    if (ogDescMeta) ogDescMeta.setAttribute('content', copy[descKey]);
  }
  document.querySelectorAll('[data-copy]').forEach(node=>{ const key=node.dataset.copy; if(copy[key])node.textContent=copy[key]; });
  ['navSutras','navThirteen','navLibrary','navData'].forEach((key,index)=>{document.querySelectorAll(`[data-copy="${key}"]`).forEach(node=>node.textContent=nav[index]);});
  const intro=document.querySelector(`[data-copy="${page}Intro"]`);if(intro)intro.textContent=copy[`${page}Intro`];
  const pageTitle=document.querySelector(`[data-copy="${page}Title"]`);if(pageTitle)pageTitle.textContent=titles[page];
  document.querySelectorAll('[data-lang-link]').forEach(link=>{link.href=pageHref(new URL(link.href).pathname);});
  document.querySelectorAll('[data-home-link]').forEach(link=>{link.href=pageHref('/');});
  document.querySelectorAll('[data-home-section]').forEach(link=>{const target=new URL(pageHref('/'),location.origin);target.hash='sutras';link.href=`${target.pathname}${target.search}${target.hash}`;});
  document.querySelectorAll('[data-reader-entry]').forEach(link=>{link.href=readerHref('T08n0251','lzh-Hant');});

  const header=document.querySelector('[data-header]');
  const setHeaderState=()=>header?.classList.toggle('scrolled',window.scrollY>24);
  setHeaderState();
  window.addEventListener('scroll',setHeaderState,{passive:true});

  const menuButton=document.querySelector('[data-menu-button]');
  const mobileMenu=document.querySelector('[data-mobile-menu]');
  const closeMenu=()=>{if(!menuButton || !mobileMenu)return;menuButton.setAttribute('aria-expanded','false');menuButton.setAttribute('aria-label',copy.menuOpen);mobileMenu.classList.remove('open');};
  if(menuButton)menuButton.setAttribute('aria-label',copy.menuOpen);
  menuButton?.addEventListener('click',()=>{const next=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(next));menuButton.setAttribute('aria-label',next?copy.menuClose:copy.menuOpen);mobileMenu?.classList.toggle('open',next);});
  mobileMenu?.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));

  const selector=document.getElementById('langSelector');
  const languageButton=selector?.querySelector('.lang-btn');
  const dropdown=document.getElementById('langDropdown');
  const closeDropdown=(restoreFocus=true)=>{if(!selector || !languageButton)return;selector.classList.remove('open');languageButton.setAttribute('aria-expanded','false');if(restoreFocus)languageButton.focus();};
  const openDropdown=()=>{if(!selector || !languageButton || !dropdown)return;selector.classList.add('open');languageButton.setAttribute('aria-expanded','true');dropdown.querySelector('li.active')?.focus();};
  if(selector && languageButton && dropdown){
    languageButton.setAttribute('aria-label',copy.language);
    const currentName=languageButton.querySelector('.current-lang-name');if(currentName)currentName.textContent=LANGUAGES[locale];
    const options=Array.from(dropdown.querySelectorAll('li[data-value]'));
    options.forEach((item,index)=>{
      const active=item.dataset.value===locale;item.classList.toggle('active',active);item.setAttribute('aria-selected',String(active));
      const selectLanguage=()=>{const value=item.dataset.value;if(!LANGUAGES[value])return;localStorage.setItem('lang',value);const next=new URL(location.href);next.searchParams.set('lang',value);location.assign(next);};
      item.addEventListener('click',event=>{event.stopPropagation();selectLanguage();});
      item.addEventListener('keydown',event=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();const delta=event.key==='ArrowDown'?1:-1;options[(index+delta+options.length)%options.length].focus();}else if(event.key==='Enter'||event.key===' '){event.preventDefault();selectLanguage();}else if(event.key==='Escape'){event.preventDefault();closeDropdown();}});
    });
    languageButton.addEventListener('click',event=>{event.stopPropagation();selector.classList.contains('open')?closeDropdown():openDropdown();});
    document.addEventListener('click',event=>{if(selector.classList.contains('open')&&!selector.contains(event.target))closeDropdown();});
  }
  document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(selector?.classList.contains('open'))closeDropdown();closeMenu();}});

  function error(container) { container.replaceChildren(el('p','error-card',copy.loadError)); }

  async function loadThirteen() {
    const list=document.querySelector('[data-thirteen-list]');
    try {
      const response=await fetch('https://buddb.xhalo.co/curated-collections/buddhist-thirteen-sutras.json',{credentials:'omit'});
      if(!response.ok)throw new Error('collection');
      const data=await response.json();if(!data || !Array.isArray(data.items))throw new Error('schema');
      const items=[...data.items].sort((a,b)=>Number(a.ordinal)-Number(b.ordinal));list.replaceChildren();
      items.forEach(item=>{
        const memberships=Array.isArray(item.memberships)?item.memberships:[];
        const primary=memberships.find(entry=>entry && entry.source==='cbeta' && entry.recommended===true && entry.completeness==='complete' && entry.relation_type==='primary_edition') || memberships.find(entry=>entry && entry.source==='cbeta' && entry.recommended===true && entry.completeness==='complete');
        const sourceId=primary && typeof primary.work_id==='string' && primary.work_id.startsWith('cbeta:')?primary.work_id.slice(6):'';
        const language=primary && safeId(primary.language,64)?primary.language:'lzh-Hant';
        const li=el('li');const row=el('div','collection-row');row.append(el('span','ordinal',String(item.ordinal).padStart(2,'0')));
        const title=el('div','sutra-title');title.append(el('h2','',locale==='zh-Hant'?item.preferred_title_zh_hant:item.preferred_title_zh_hans));title.append(el('p','',item.preferred_title_zh_hant || ''));if(item.title_sanskrit)title.append(el('small','',item.title_sanskrit));row.append(title);
        const meta=el('dl','meta');[[copy.sourceId,safeId(sourceId)?sourceId:'—'],[copy.translator,primary?.translator || '—'],[copy.relation,primary?.relation_type || '—'],[copy.completeness,primary?.completeness || '—']].forEach(([term,value])=>{const wrap=el('div');wrap.append(el('dt','',term),el('dd','',value));meta.append(wrap);});row.append(meta);
        if(safeId(sourceId)){const link=el('a','read-link',copy.read);link.href=readerHref(sourceId,language);row.append(link);}li.append(row);
        const others=memberships.filter(entry=>entry!==primary);
        if(others.length){const details=el('details');details.append(el('summary','',`${copy.alternates} · ${others.length}`));const wrap=el('div','alternate-wrap');const table=el('table');const head=el('thead');const hr=el('tr');[copy.versionTitle,copy.translator,copy.source,copy.languageLabel,copy.relation,copy.completeness,copy.recommended].forEach(value=>hr.append(el('th','',value)));head.append(hr);const body=el('tbody');others.forEach(entry=>{const tr=el('tr');[entry.title,entry.translator || '—',entry.source,entry.language,entry.relation_type,entry.completeness,entry.recommended?copy.recommended:'—'].forEach(value=>tr.append(el('td','',value || '—')));body.append(tr);});table.append(head,body);wrap.append(table);details.append(wrap);li.append(details);}list.append(li);
      });
      const scope=document.querySelector('[data-scope]');scope.textContent=data.scope_note || data.description || '';
      document.querySelector('[data-contract]').textContent=`schema ${data.schema_version} · collection ${data.version} · data ${data.data_version}`;
    } catch { error(list); }
  }

  async function loadLibrary() {
    const list=document.querySelector('[data-library-list]');const summary=document.querySelector('[data-catalog-summary]');
    const requestedPage=Math.max(1,Number.parseInt(params.get('page') || '1',10) || 1);const limit=50;
    try {
      const response=await fetch(`https://foread.xhalo.co/api/catalog?source=cbeta&offset=${(requestedPage-1)*limit}&limit=${limit}`,{credentials:'omit',mode:'cors'});if(!response.ok)throw new Error('catalog');
      const data=await response.json();if(!data || !Number.isSafeInteger(data.total) || !Array.isArray(data.items))throw new Error('schema');
      const totalPages=Math.max(1,Math.ceil(data.total/limit));const current=Math.min(requestedPage,totalPages);if(current!==requestedPage){location.replace(pageHref('/library/',{page:current}));return;}
      const render=(items)=>{list.replaceChildren();items.forEach((item,index)=>{if(!item || !safeId(item.sourceId))return;const language=Array.isArray(item.languages)&&item.languages.find(value=>safeId(value,64)) || 'lzh-Hant';const li=el('li');li.append(el('span','ordinal',String((current-1)*limit+index+1).padStart(4,'0')));const title=el('div');title.append(el('h2','',String(item.title || item.sourceId).slice(0,240)),el('small','',`${item.sourceId} · ${language}`));li.append(title);const link=el('a','read-link',copy.read);link.href=readerHref(item.sourceId,language,`?from=library&page=${current}`);li.append(link);list.append(li);});if(!list.children.length)list.append(el('li','error-card',copy.loadError));};
      render(data.items);summary.textContent=format(copy.totalSummary,{total:data.total,from:data.total?(current-1)*limit+1:0,to:Math.min(current*limit,data.total)});
      const pagination=document.querySelector('[data-pagination]');if(current>1){const prev=el('a','',copy.previous);prev.href=pageHref('/library/',{page:current-1});pagination.append(prev);}else pagination.append(el('span'));
      pagination.append(el('span','',format(copy.pageSummary,{page:current,pages:totalPages,remaining:totalPages-current})));
      if(current<totalPages){const next=el('a','',copy.next);next.href=pageHref('/library/',{page:current+1});pagination.append(next);}else pagination.append(el('span'));
      const filter=document.querySelector('[data-library-filter]');filter.addEventListener('input',()=>{const query=filter.value.trim().toLocaleLowerCase(locale);render(data.items.filter(item=>String(item.title).toLocaleLowerCase(locale).includes(query)||item.sourceId.toLowerCase().includes(query)));});
    } catch { error(list);summary.textContent=copy.loadError; }
  }

  async function loadData() {
    const container=document.querySelector('[data-data-status]');
    try {const response=await fetch('https://buddb.xhalo.co/latest.json',{credentials:'omit'});if(!response.ok)throw new Error('latest');const data=await response.json();const dl=el('dl');[[copy.buildVersion,data.version],[copy.buildTime,data.build_time],[copy.schema,data.schema_version],[copy.works,data.counts?.works],[copy.status,data.release_status]].forEach(([term,value],index)=>{const wrap=el('div');wrap.append(el('dt','',term),el('dd',index===4&&value==='complete'?'healthy':'',String(value ?? '—')));dl.append(wrap);});container.replaceChildren(...dl.children);}catch{error(container);}
  }

  if(page==='thirteen')void loadThirteen();
  if(page==='library')void loadLibrary();
  if(page==='data')void loadData();
})();
